image: nixos/unstable
sources:
  - git@github.com:colemickens/nixpkgs-wayland
secrets:
  - df3e056f-2931-4a93-86db-e40c2fa6098d # cachix.dhall
  - bd070f2a-01d1-4b7b-9795-036deb06912c # id_ed25519
environment:
  CI_BUILD: "sr.ht"
tasks:
  # prep in a non-pure nix-shell, relies on git+openssh+cacert at least
  - prep: |
      cd nixpkgs-wayland
      nix-shell -I 'https://github.com/nixos/nixpkgs/archive/nixos-unstable.tar.gz' -p nixUnstable --command "./.ci/prep.sh"
  - update: |
      cd nixpkgs-wayland
      nix-shell --pure --command "JOB_ID=$JOB_ID ./update.sh"
triggers:
  - action: webhook
    condition: failure
    url: https://discord.com/api/webhooks/786020673335459881/_iF0A1DjKcoOwrKamznaXdFge-PQw6tWl-ZNphX98SnqYY3D32PsZDFjqTelSLdVY_mj
